{
 "title": "SRv6 FlexAlgo Telemetry (Nokia SR OS)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   { "name": "Interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WAN nodes",
   "type": "andrewbmchugh-flow-panel",
   "description": "Physical layout",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_sros_if_oper_state_state_router_interface_oper_state",
     "legendFormat": "sros_if_oper_state:{{source}}:{{interface_interface_name}}"
    },
    {
     "expr": "gnmic_sros_vprn_if_oper_state_state_service_vprn_interface_oper_state",
     "legendFormat": "sros_vprn_if_oper_state:{{source}}:{{interface_interface_name}}"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_stats_state_router_interface_statistics_ip_in_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[1m])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} IN"
    },
    {
     "expr": "-rate(gnmic_sros_if_stats_state_router_interface_statistics_ip_out_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[1m])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} OUT"
    }
   ]
  },
  {
   "title": "VPRN 50 (Transport: SRv6, FlexAlgo 128 / Service: EVPN IFL) - Links Bandwidth & Delay",
   "type": "andrewbmchugh-flow-panel",
   "description": "vprn_using_flex-algo_128_srv6",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_stats_state_router_interface_statistics_ip_out_octets[30s])*8",
     "legendFormat": "{{source}}:{{interface_interface_name}}:ip:out"
    },
    {
     "expr": "rate(gnmic_sros_if_stats_state_router_interface_statistics_ip_in_octets[30s])*8",
     "legendFormat": "{{source}}:{{inerface_interface_name}}:ip:in"
    },
    {
     "expr": "rate(gnmic_sros_vprn_if_stats_state_service_vprn_interface_statistics_ip_out_octets[30s])*8",
     "legendFormat": "{{source}}:{{inerface_interface_name}}:vprn:out"
    },
    {
     "expr": "rate(gnmic_sros_vprn_if_stats_state_service_vprn_interface_statistics_ip_in_octets[30s])*8",
     "legendFormat": "{{source}}:{{inerface_interface_name}}:vprn:in"
    },
    {
     "expr": "gnmic_sros_if_dyn_delay_stats_state_test_oam_link_measurement_router_interface_last_reported_delay",
     "legendFormat": "{{source}}:{{interface_interface_name}}:delay"
    }
   ]
  },
  {
   "title": "SRv6 FlexAlgo128 Locator Routes Metric (IPv6 route table)",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "gnmic_sros_route_table_unicast_ipv6_stats_state_router_route_table_unicast_ipv6_route_nexthop_metric{route_ipv6_prefix=~\"c128.*/64\"} and gnmic_sros_route_table_unicast_ipv6_stats_state_router_route_table_unicast_ipv6_route_nexthop_metric != 0",
     "legendFormat": "{{source}}, netIns={{route_ipv6_prefix}}, {{nexthop_nexthop_ip}}"
    }
   ]
  },
  {
   "title": "Total BGP Peers #",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_peer_stats_state_router_bgp_statistics_peers{router_router_name=~\"$network_instance\",source=~\"$NE\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "BGP VPN IPv4 Routing Stats",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_vpn_ipv4_routes_state_router_bgp_statistics_routes_per_family_vpn_ipv4_remote_active_routes{router_router_name=~\"$network_instance\",source=~\"$NE\"}",
     "legendFormat": "{{source}}, Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv4_routes_total_routes{network_instance_name=~\"$network_instance\",source=~\"$NE\"}",
     "legendFormat": "{{source}}, netIns={{network_instance_name}}, Total Routes"
    }
   ]
  },
  {
   "title": "BGP VPN IPv6 Routing Stats",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_vpn_ipv6_routes_state_router_bgp_statistics_routes_per_family_vpn_ipv6_remote_active_routes{router_router_name=\"Base\",source=~\"$NE\"}",
     "legendFormat": "{{source}} Active Routes"
    },
    {
     "expr": "gnmic_srl_ipv6_routes_total_routes{network_instance_name=\"default\",source=~\"$NE\"}",
     "legendFormat": "{{source}} Total Routes"
    },
    {
     "expr": "gnmic_srl_ipv6_routes_active_routes_with_ecmp{network_instance_name=\"default\",source=~\"$NE\"}",
     "legendFormat": "{{source}} Active ECMP Routes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_state_system_cpu_summary_usage_cpu_usage{source=~\"$NE\"}",
     "legendFormat": "{{source}} Total Instant"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_total_in_use{source=~\"$NE\"}",
     "legendFormat": "{{source}} free mem"
    },
    {
     "expr": "gnmic_sros_mem_available_memory{source=~\"$NE\"}",
     "legendFormat": "{{source}} physical mem"
    }
   ]
  }
 ]
}